patch to rosmake error due to .h not found
I get the following error w/o this patch. Ubuntu 12.10, ROS Groovy

```
$ rosmake marble_plugin
[ rosmake ] rosmake starting...                                                                                                   :
[rosmake-5] Starting >>> marble_plugin [ make ]
[ rosmake ] Last 40 linesrble_plugin: 3.3 sec ]   [ 1 Active 37/38 Complete ] {-------------------------------------------------------------------------------
  CMake Warning:
    Manually-specified variables were not used by the project:
  
      CMAKE_TOOLCHAIN_FILE
  
  
  -- Build files have been written to: /home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build
  cd build && make -j -l8
  make[1]: Entering directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  make[2]: Entering directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  make[3]: Entering directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  make[3]: Leaving directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  [  0%] Built target rospack_genmsg_libexe
  make[3]: Entering directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  make[3]: Leaving directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  [  0%] Built target rosbuild_precompile
  make[3]: Entering directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  [ 25%] Generating ui_marble_plugin.h
  Scanning dependencies of target marble_plugin
  make[3]: Leaving directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  make[3]: Entering directory `/home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build'
  [ 50%] [ 75%] Building CXX object src/marble_plugin/CMakeFiles/marble_plugin.dir/marble_plugin.cpp.o
  Building CXX object src/marble_plugin/CMakeFiles/marble_plugin.dir/moc_marble_plugin.cxx.o
  In file included from /home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/src/marble_plugin/marble_plugin.h:46:0,
                   from /home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/src/marble_plugin/marble_plugin.cpp:41:
  /home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build/src/marble_plugin/ui_marble_plugin.h:26:26: fatal error: MarbleWidget.h: No such file or directory
  compilation terminated.
  In file included from /home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build/src/marble_plugin/../../../src/marble_plugin/marble_plugin.h:46:0,
                   from /home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build/src/marble_plugin/moc_marble_plugin.cxx:10:
  /home/user/ROS/groovy_quantal/yet_catkinized_ws/marble_plugin/build/src/marble_plugin/ui_marble_plugin.h:26:26: fatal error: MarbleWidget.h: No such file or directory
  compilation terminated.
```